version: "3.8"

services:
  user-service:
    container_name: task-user-service
    build: ./user-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/user-service
    depends_on:
      - mongo
    volumes:
      - ./user-service:/app
      - /app/node_modules

  mongo:
    container_name: task-mongo-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
